version: '2'
services:
  db:
    image: mydb2
    container_name: mydb2
    privileged: true
    ports:
      - 50000:50000
    volumes:
      - ./db2:/database
    environment:
      - DB2INST1_PASSWORD=db2int1
      - LICENSE=accept
      - DBNAME=homesalesdb
    command: bash -c "/var/custom/custom/run.sh"